$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1421491590893.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7279516462224c7c934aec7136255c59",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"421ffac4d4634120a6ce63ee299fa467",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c9244275e3aa436b9ff9b6a761fafe54"},
{
          "id":"31ec9056b6e64228902c35eb22caefa4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":420}},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"51712b1429cd4cfca22a4342d969f383"},
{
          "id":"cbdcc14e7a80468fbea93372431c2866",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":140,
              "y":10},
            "size":{
              "width":40,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":40,
                "height":23}}},
          "objects":[{
              "id":"34b7a8737a5f4a2e8a1d6996e5e7832a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":140,
                  "y":10},
                "size":{
                  "width":40,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"87e966b53cc24594a121f9411a0d1c02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":64},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":92,
                "height":16}}},
          "objects":[{
              "id":"9f3e90941a6849889bd313217f536bab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":64},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"6ea509be8e0b475b971102e7001365bb",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0ed0e86cef454d66883dfcc6b88d06fd",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b492e50458ec491e9e4bcb92cc4a91fb",
                  "label":"",
                  "parentDynamicPanel":"6ea509be8e0b475b971102e7001365bb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":120}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"0c1303aea7644c0986903ec2bce909a8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6ea509be8e0b475b971102e7001365bb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":120}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u18.png"}},
{
                  "id":"f5f7c36543344361babaddb2ba1e4628",
                  "label":"",
                  "parentDynamicPanel":"6ea509be8e0b475b971102e7001365bb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":40,
                        "height":16}}},
                  "objects":[{
                      "id":"6b8c39bd8aa4438c9d4cce36909019a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6ea509be8e0b475b971102e7001365bb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"792c49b767c74fe495939965b8d65f51",
                  "label":"",
                  "parentDynamicPanel":"6ea509be8e0b475b971102e7001365bb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":36},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"78aad83816164a229f5f097de2f4ed1d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6ea509be8e0b475b971102e7001365bb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":36},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"f313c0c2783d4eceb6a509c4a9136663",
                  "label":"",
                  "parentDynamicPanel":"6ea509be8e0b475b971102e7001365bb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":62},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":79,
                        "height":16}}},
                  "objects":[{
                      "id":"d44f2fc6054a4e0eb9fc202ca39724a0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6ea509be8e0b475b971102e7001365bb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":62},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"6e5151feddb14055a879f1ac031e8f53",
                  "label":"",
                  "parentDynamicPanel":"6ea509be8e0b475b971102e7001365bb",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":250,
                      "y":16.5},
                    "size":{
                      "width":60,
                      "height":55}},
                  "adaptiveStyles":{
                    "a":{
}}},
{
                  "id":"f0a218d6a69c4208a3a9e03629f2d335",
                  "label":"",
                  "parentDynamicPanel":"6ea509be8e0b475b971102e7001365bb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":90},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"ba32ff9073b444529a626bee2357b671",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6ea509be8e0b475b971102e7001365bb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":90},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"3bd635a0dea143ab952ce72af40d4adb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":142},
            "size":{
              "width":144,
              "height":32}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":144,
                "height":32}}},
          "objects":[{
              "id":"d413b94994d344f4a7d047c8ca05cb09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":142},
                "size":{
                  "width":144,
                  "height":32}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"3c783d4f053b47c5a135e9097ce66528",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":210},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a4574cca43df414f8269384ee512b06f",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"45c74cbe52484a409b45387852616a58",
                  "label":"",
                  "parentDynamicPanel":"3c783d4f053b47c5a135e9097ce66528",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":120}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"d0693a9bef3c4ca6a119efe03b1b1bdd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c783d4f053b47c5a135e9097ce66528",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":120}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u18.png"}},
{
                  "id":"cf1e708502e74207aab048f10b39167f",
                  "label":"",
                  "parentDynamicPanel":"3c783d4f053b47c5a135e9097ce66528",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":40,
                        "height":16}}},
                  "objects":[{
                      "id":"8f7085e6d74145c7b0e4c61cf5598986",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c783d4f053b47c5a135e9097ce66528",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"d3e31518547d416a92168f7882e4102a",
                  "label":"",
                  "parentDynamicPanel":"3c783d4f053b47c5a135e9097ce66528",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":36},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"5cdaf8546f0045a080991fc49b081adb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c783d4f053b47c5a135e9097ce66528",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":36},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"7d82e5a93ebd4c1dac0c45365e5c63bf",
                  "label":"",
                  "parentDynamicPanel":"3c783d4f053b47c5a135e9097ce66528",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":62},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":79,
                        "height":16}}},
                  "objects":[{
                      "id":"ac5c642c0a994113b8fae5312ce3b6d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c783d4f053b47c5a135e9097ce66528",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":62},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"975cd21f1b3944438283b6f708fa73b2",
                  "label":"",
                  "parentDynamicPanel":"3c783d4f053b47c5a135e9097ce66528",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":250,
                      "y":16.5},
                    "size":{
                      "width":60,
                      "height":55}},
                  "adaptiveStyles":{
                    "a":{
}}},
{
                  "id":"a770721fe7aa4617ad00aef27f60d15a",
                  "label":"",
                  "parentDynamicPanel":"3c783d4f053b47c5a135e9097ce66528",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":90},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"ac2c5a9081644eed9b6fcdfce1675654",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c783d4f053b47c5a135e9097ce66528",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":90},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"96aab6c491974684a181e9a6e240aa94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":224},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":144,
                "height":16}}},
          "objects":[{
              "id":"034c92621e324c4fb1dfcb9422276117",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":224},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c9244275e3aa436b9ff9b6a761fafe54":{
      "packageId":"c9244275e3aa436b9ff9b6a761fafe54",
      "type":"Axure:Master",
      "name":"上导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"362ac4472cf34d7cbe59b95da5fd92f9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"7d5983b6bab84de483fd1fed0e7ba98f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/登录界面/u0.png"}},
{
            "id":"05b4fb99562b4ceea301650e882e7eb8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":50}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"9476162c387f47359880aa58e3bdf455",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":50}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"5a3fd74cc3984739a980ea09882e94f1",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12},
              "size":{
                "width":60,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}}},
{
            "id":"2e6ef4a2c9554d5b9f1cec0e24e06e53",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":249,
                "y":12},
              "size":{
                "width":60,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}}}]}},
    "51712b1429cd4cfca22a4342d969f383":{
      "packageId":"51712b1429cd4cfca22a4342d969f383",
      "type":"Axure:Master",
      "name":"底部导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"dbf88162755142e08204fcfe620f9439",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":455},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":0,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"a94363e385794ed6950cbb4c15dd73a4",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":430},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":64,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的排期",
                        "target":{
                          "targetType":"page",
                          "url":"我的排期.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"94fc8cf3d1d34f9f9eb5d0d8a2249caa",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":440},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":128,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的信息",
                        "target":{
                          "targetType":"page",
                          "url":"我的信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"ab56bfc79a1247568a0df315cb300dc8",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":450},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":192,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 平台咨询",
                        "target":{
                          "targetType":"page",
                          "url":"平台咨询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"ef2472d415f44a439e9ffc61b0368de5",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":460},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":256,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 账户余额",
                        "target":{
                          "targetType":"page",
                          "url":"账户余额.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "421ffac4d4634120a6ce63ee299fa467":{
      "scriptId":"u0",
      "362ac4472cf34d7cbe59b95da5fd92f9":{
        "scriptId":"u1"},
      "7d5983b6bab84de483fd1fed0e7ba98f":{
        "scriptId":"u2"},
      "05b4fb99562b4ceea301650e882e7eb8":{
        "scriptId":"u3"},
      "9476162c387f47359880aa58e3bdf455":{
        "scriptId":"u4"},
      "5a3fd74cc3984739a980ea09882e94f1":{
        "scriptId":"u5"},
      "2e6ef4a2c9554d5b9f1cec0e24e06e53":{
        "scriptId":"u6"}},
    "31ec9056b6e64228902c35eb22caefa4":{
      "scriptId":"u7",
      "dbf88162755142e08204fcfe620f9439":{
        "scriptId":"u8"},
      "a94363e385794ed6950cbb4c15dd73a4":{
        "scriptId":"u9"},
      "94fc8cf3d1d34f9f9eb5d0d8a2249caa":{
        "scriptId":"u10"},
      "ab56bfc79a1247568a0df315cb300dc8":{
        "scriptId":"u11"},
      "ef2472d415f44a439e9ffc61b0368de5":{
        "scriptId":"u12"}},
    "cbdcc14e7a80468fbea93372431c2866":{
      "scriptId":"u13"},
    "34b7a8737a5f4a2e8a1d6996e5e7832a":{
      "scriptId":"u14"},
    "87e966b53cc24594a121f9411a0d1c02":{
      "scriptId":"u15"},
    "9f3e90941a6849889bd313217f536bab":{
      "scriptId":"u16"},
    "6ea509be8e0b475b971102e7001365bb":{
      "scriptId":"u17"},
    "b492e50458ec491e9e4bcb92cc4a91fb":{
      "scriptId":"u18"},
    "0c1303aea7644c0986903ec2bce909a8":{
      "scriptId":"u19"},
    "f5f7c36543344361babaddb2ba1e4628":{
      "scriptId":"u20"},
    "6b8c39bd8aa4438c9d4cce36909019a4":{
      "scriptId":"u21"},
    "792c49b767c74fe495939965b8d65f51":{
      "scriptId":"u22"},
    "78aad83816164a229f5f097de2f4ed1d":{
      "scriptId":"u23"},
    "f313c0c2783d4eceb6a509c4a9136663":{
      "scriptId":"u24"},
    "d44f2fc6054a4e0eb9fc202ca39724a0":{
      "scriptId":"u25"},
    "6e5151feddb14055a879f1ac031e8f53":{
      "scriptId":"u26"},
    "f0a218d6a69c4208a3a9e03629f2d335":{
      "scriptId":"u27"},
    "ba32ff9073b444529a626bee2357b671":{
      "scriptId":"u28"},
    "3bd635a0dea143ab952ce72af40d4adb":{
      "scriptId":"u29"},
    "d413b94994d344f4a7d047c8ca05cb09":{
      "scriptId":"u30"},
    "3c783d4f053b47c5a135e9097ce66528":{
      "scriptId":"u31"},
    "45c74cbe52484a409b45387852616a58":{
      "scriptId":"u32"},
    "d0693a9bef3c4ca6a119efe03b1b1bdd":{
      "scriptId":"u33"},
    "cf1e708502e74207aab048f10b39167f":{
      "scriptId":"u34"},
    "8f7085e6d74145c7b0e4c61cf5598986":{
      "scriptId":"u35"},
    "d3e31518547d416a92168f7882e4102a":{
      "scriptId":"u36"},
    "5cdaf8546f0045a080991fc49b081adb":{
      "scriptId":"u37"},
    "7d82e5a93ebd4c1dac0c45365e5c63bf":{
      "scriptId":"u38"},
    "ac5c642c0a994113b8fae5312ce3b6d1":{
      "scriptId":"u39"},
    "975cd21f1b3944438283b6f708fa73b2":{
      "scriptId":"u40"},
    "a770721fe7aa4617ad00aef27f60d15a":{
      "scriptId":"u41"},
    "ac2c5a9081644eed9b6fcdfce1675654":{
      "scriptId":"u42"},
    "96aab6c491974684a181e9a6e240aa94":{
      "scriptId":"u43"},
    "034c92621e324c4fb1dfcb9422276117":{
      "scriptId":"u44"}}});