$axure.loadCurrentPage({
  "url":"我的信息.html",
  "generationDate":new Date(1421557818867.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"066ee639f1ff4036a97cc796a65566af",
    "type":"Axure:Page",
    "name":"我的信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"030c15e2e06d46e8a3c9521a7fa8fd2b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c9244275e3aa436b9ff9b6a761fafe54"},
{
          "id":"81e474d3dfee4d50bbf9fbd64e7c57e5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":420}},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"51712b1429cd4cfca22a4342d969f383"},
{
          "id":"3f55eaa97ea44892af7e20409d6e6ea9",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":200},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5342edcbd4c04fd09a5c53d6c58a5a5a",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e544687f2f194e1284a43e92555b27df",
                  "label":"",
                  "parentDynamicPanel":"3f55eaa97ea44892af7e20409d6e6ea9",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":61}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"aa673584a2134cd2be4fc20cf0cd30a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3f55eaa97ea44892af7e20409d6e6ea9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":61}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的信息/u14.png"}},
{
                  "id":"68321a0dfb214a029d675c2d0a4ba71b",
                  "label":"",
                  "parentDynamicPanel":"3f55eaa97ea44892af7e20409d6e6ea9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":0},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"2503c58d81b54e01baa6cf4ec3da7590",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3f55eaa97ea44892af7e20409d6e6ea9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":0},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"3e94f60baefa4694a5ed6861e3057eaf",
                  "label":"",
                  "parentDynamicPanel":"3f55eaa97ea44892af7e20409d6e6ea9",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":26},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
                    "a":{
}}}]}]},
{
          "id":"bf9109f3c6d947519225f6ee224a021d",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":261},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d1aad331b1d14b73aff47e18749a378b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"941e5fce808b440892ffad55f899f0c0",
                  "label":"",
                  "parentDynamicPanel":"bf9109f3c6d947519225f6ee224a021d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":61}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"841fb47b6f204e3b99876ba143915317",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf9109f3c6d947519225f6ee224a021d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":61}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的信息/u14.png"}},
{
                  "id":"e4fc23faa5dd41caa6e09458ef3907d8",
                  "label":"",
                  "parentDynamicPanel":"bf9109f3c6d947519225f6ee224a021d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":8},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":79,
                        "height":16}}},
                  "objects":[{
                      "id":"5918bc9d6e534937988c609966da2fe1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf9109f3c6d947519225f6ee224a021d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":8},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"6e69f5cf864a4e8bbbdcab86201aa61c",
                  "label":"",
                  "parentDynamicPanel":"bf9109f3c6d947519225f6ee224a021d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":34},
                    "size":{
                      "width":43,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":43,
                        "height":16}}},
                  "objects":[{
                      "id":"3126723f479e4bfbac2bd04baa743425",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf9109f3c6d947519225f6ee224a021d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":34},
                        "size":{
                          "width":43,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"9d096e89494d417a8e05bd9bf3e1c9c7",
                  "label":"",
                  "parentDynamicPanel":"bf9109f3c6d947519225f6ee224a021d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":78,
                      "y":34},
                    "size":{
                      "width":39,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":39,
                        "height":16}}},
                  "objects":[{
                      "id":"8dbb7cca515b40d5b673b0974410b261",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf9109f3c6d947519225f6ee224a021d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":78,
                          "y":34},
                        "size":{
                          "width":39,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"4c28f5a4e3f04ea3af89aa07e942b649",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":320},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"35fde842207d4fd3a6c05d3c20a697bc",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"06742d7546884d69af933d133b3bd909",
                  "label":"",
                  "parentDynamicPanel":"4c28f5a4e3f04ea3af89aa07e942b649",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":60}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"59caa0159ebb402fb472cdb9fe708bdb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4c28f5a4e3f04ea3af89aa07e942b649",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":60}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的信息/u29.png"}},
{
                  "id":"dd74676da7e24a06ae0b36fb4d799607",
                  "label":"",
                  "parentDynamicPanel":"4c28f5a4e3f04ea3af89aa07e942b649",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":12},
                    "size":{
                      "width":105,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":105,
                        "height":16}}},
                  "objects":[{
                      "id":"7a005422ea98400193c6497629c72f08",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4c28f5a4e3f04ea3af89aa07e942b649",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":12},
                        "size":{
                          "width":105,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"20ee58b3bb164ef3959856055cf84832",
                  "label":"",
                  "parentDynamicPanel":"4c28f5a4e3f04ea3af89aa07e942b649",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":38},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":31,
                        "height":16}}},
                  "objects":[{
                      "id":"ad09903c3cc948b89fa9af3f0ff1ab0d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4c28f5a4e3f04ea3af89aa07e942b649",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":38},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"005d5ff0f2d44f1cbc4cf9df78198c81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":348,
              "y":212},
            "size":{
              "width":105,
              "height":32}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":105,
                "height":32}}},
          "objects":[{
              "id":"a93cb542e5ed4aafbeab49fc43827fd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":348,
                  "y":212},
                "size":{
                  "width":105,
                  "height":32}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"ba78ff37a9ee46c38dd0ca296fc6574c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":320,
              "height":150}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"4110cba918064b56a7d10f0ee3db7ae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":320,
                  "height":150}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/我的信息/u37.png"}},
{
          "id":"4645c90fe3494ba4bc442bebb1d7f09c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":280},
            "size":{
              "width":290,
              "height":100}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"1649129e9f664d7f805bf2fd0d5e1f74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":280},
                "size":{
                  "width":290,
                  "height":100}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/我的信息/u39.png"}},
{
          "id":"627357e7ec544b0788b1b79077eddb00",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":280},
            "size":{
              "width":290,
              "height":100}},
          "adaptiveStyles":{
            "a":{
}}},
{
          "id":"d72fc30c95bb403dafc9287f33c2a345",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":380},
            "size":{
              "width":290,
              "height":40}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 密码修改界面",
                      "target":{
                        "targetType":"page",
                        "url":"密码修改界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9f2c8016d54c4642aa69666ba5070aee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":7},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":7},
              "size":{
                "width":81,
                "height":23}}},
          "objects":[{
              "id":"c9980235b2a6410bbfa57e8749ffde0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":7},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c9244275e3aa436b9ff9b6a761fafe54":{
      "packageId":"c9244275e3aa436b9ff9b6a761fafe54",
      "type":"Axure:Master",
      "name":"上导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"362ac4472cf34d7cbe59b95da5fd92f9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"7d5983b6bab84de483fd1fed0e7ba98f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/登录界面/u0.png"}},
{
            "id":"05b4fb99562b4ceea301650e882e7eb8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":50}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"9476162c387f47359880aa58e3bdf455",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":50}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"5a3fd74cc3984739a980ea09882e94f1",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12},
              "size":{
                "width":60,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}}},
{
            "id":"2e6ef4a2c9554d5b9f1cec0e24e06e53",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":249,
                "y":12},
              "size":{
                "width":60,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}}}]}},
    "51712b1429cd4cfca22a4342d969f383":{
      "packageId":"51712b1429cd4cfca22a4342d969f383",
      "type":"Axure:Master",
      "name":"底部导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"dbf88162755142e08204fcfe620f9439",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":455},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":0,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"a94363e385794ed6950cbb4c15dd73a4",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":430},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":64,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的排期",
                        "target":{
                          "targetType":"page",
                          "url":"我的排期.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"94fc8cf3d1d34f9f9eb5d0d8a2249caa",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":440},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":128,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的信息",
                        "target":{
                          "targetType":"page",
                          "url":"我的信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"ab56bfc79a1247568a0df315cb300dc8",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":450},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":192,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 平台咨询",
                        "target":{
                          "targetType":"page",
                          "url":"平台咨询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"ef2472d415f44a439e9ffc61b0368de5",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":460},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":256,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 账户余额",
                        "target":{
                          "targetType":"page",
                          "url":"账户余额.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "030c15e2e06d46e8a3c9521a7fa8fd2b":{
      "scriptId":"u0",
      "362ac4472cf34d7cbe59b95da5fd92f9":{
        "scriptId":"u1"},
      "7d5983b6bab84de483fd1fed0e7ba98f":{
        "scriptId":"u2"},
      "05b4fb99562b4ceea301650e882e7eb8":{
        "scriptId":"u3"},
      "9476162c387f47359880aa58e3bdf455":{
        "scriptId":"u4"},
      "5a3fd74cc3984739a980ea09882e94f1":{
        "scriptId":"u5"},
      "2e6ef4a2c9554d5b9f1cec0e24e06e53":{
        "scriptId":"u6"}},
    "81e474d3dfee4d50bbf9fbd64e7c57e5":{
      "scriptId":"u7",
      "dbf88162755142e08204fcfe620f9439":{
        "scriptId":"u8"},
      "a94363e385794ed6950cbb4c15dd73a4":{
        "scriptId":"u9"},
      "94fc8cf3d1d34f9f9eb5d0d8a2249caa":{
        "scriptId":"u10"},
      "ab56bfc79a1247568a0df315cb300dc8":{
        "scriptId":"u11"},
      "ef2472d415f44a439e9ffc61b0368de5":{
        "scriptId":"u12"}},
    "3f55eaa97ea44892af7e20409d6e6ea9":{
      "scriptId":"u13"},
    "e544687f2f194e1284a43e92555b27df":{
      "scriptId":"u14"},
    "aa673584a2134cd2be4fc20cf0cd30a2":{
      "scriptId":"u15"},
    "68321a0dfb214a029d675c2d0a4ba71b":{
      "scriptId":"u16"},
    "2503c58d81b54e01baa6cf4ec3da7590":{
      "scriptId":"u17"},
    "3e94f60baefa4694a5ed6861e3057eaf":{
      "scriptId":"u18"},
    "bf9109f3c6d947519225f6ee224a021d":{
      "scriptId":"u19"},
    "941e5fce808b440892ffad55f899f0c0":{
      "scriptId":"u20"},
    "841fb47b6f204e3b99876ba143915317":{
      "scriptId":"u21"},
    "e4fc23faa5dd41caa6e09458ef3907d8":{
      "scriptId":"u22"},
    "5918bc9d6e534937988c609966da2fe1":{
      "scriptId":"u23"},
    "6e69f5cf864a4e8bbbdcab86201aa61c":{
      "scriptId":"u24"},
    "3126723f479e4bfbac2bd04baa743425":{
      "scriptId":"u25"},
    "9d096e89494d417a8e05bd9bf3e1c9c7":{
      "scriptId":"u26"},
    "8dbb7cca515b40d5b673b0974410b261":{
      "scriptId":"u27"},
    "4c28f5a4e3f04ea3af89aa07e942b649":{
      "scriptId":"u28"},
    "06742d7546884d69af933d133b3bd909":{
      "scriptId":"u29"},
    "59caa0159ebb402fb472cdb9fe708bdb":{
      "scriptId":"u30"},
    "dd74676da7e24a06ae0b36fb4d799607":{
      "scriptId":"u31"},
    "7a005422ea98400193c6497629c72f08":{
      "scriptId":"u32"},
    "20ee58b3bb164ef3959856055cf84832":{
      "scriptId":"u33"},
    "ad09903c3cc948b89fa9af3f0ff1ab0d":{
      "scriptId":"u34"},
    "005d5ff0f2d44f1cbc4cf9df78198c81":{
      "scriptId":"u35"},
    "a93cb542e5ed4aafbeab49fc43827fd8":{
      "scriptId":"u36"},
    "ba78ff37a9ee46c38dd0ca296fc6574c":{
      "scriptId":"u37"},
    "4110cba918064b56a7d10f0ee3db7ae1":{
      "scriptId":"u38"},
    "4645c90fe3494ba4bc442bebb1d7f09c":{
      "scriptId":"u39"},
    "1649129e9f664d7f805bf2fd0d5e1f74":{
      "scriptId":"u40"},
    "627357e7ec544b0788b1b79077eddb00":{
      "scriptId":"u41"},
    "d72fc30c95bb403dafc9287f33c2a345":{
      "scriptId":"u42"},
    "9f2c8016d54c4642aa69666ba5070aee":{
      "scriptId":"u43"},
    "c9980235b2a6410bbfa57e8749ffde0d":{
      "scriptId":"u44"}}});