$axure.loadCurrentPage({
  "url":"订单详情页面.html",
  "generationDate":new Date(1421557820256.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8cd6fa078609474398185eee1b3c1d72",
    "type":"Axure:Page",
    "name":"订单详情页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"20973d8365994f5ba7c5531b80fd7d71",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"df7296c8ffe54f5a8275e259720d080f"},
{
          "id":"b87afb901fec4bfdaca9cc5a4922f541",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":130,
              "y":10},
            "size":{
              "width":61,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":61,
                "height":23}}},
          "objects":[{
              "id":"9c1ff02a5a694aebae0614fe9dc08441",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":130,
                  "y":10},
                "size":{
                  "width":61,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"a629fb25bb48430f9b9e03a6bcbb0b77",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"aba7ab7314434f1a8c51811e3a7cef68",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b4c583531fb0460eaac14e492d39d7c9",
                  "label":"",
                  "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":110}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"c1f54f7bc0514a088b665e3d11678ebb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":110}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/订单详情页面/u9.png"}},
{
                  "id":"6de7e3e051934305a9a4d5f1e5f9181a",
                  "label":"",
                  "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"b98fcc64610845e49c3c78a31a7f6033",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"49d57e39954f475baa6f2d5094a24115",
                  "label":"",
                  "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":36},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"c8324e40ea3648d79796ba60437a1a25",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":36},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"f38afb9e27b2448087f9df8143157ea9",
                  "label":"",
                  "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":147,
                      "y":36},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"69547f8620734a86ad870ffcc51c6bf7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":147,
                          "y":36},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"4864e65259dd4b8ba22a50fc67743efa",
                  "label":"",
                  "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":62},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":79,
                        "height":16}}},
                  "objects":[{
                      "id":"0678aaace7ac4e3988ccc0275b827bb7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":62},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"709a3d66e3c74fceb849ac302497403f",
                  "label":"",
                  "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":88},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"57afb92a0e4349f386ad9dece6e6725c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a629fb25bb48430f9b9e03a6bcbb0b77",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":88},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"3b2ccaa7ce854bbc8685b9b16b33bb4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":170},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":79,
                "height":16}}},
          "objects":[{
              "id":"4bc02d41da3040888f0dd5ededb3cd6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":170},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"23114f8bdcf241c688f3039672270031",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":190},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e7c54562d71a491e9ee7e403cb59e471",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c880b924fe944950b104273ee734aae9",
                  "label":"",
                  "parentDynamicPanel":"23114f8bdcf241c688f3039672270031",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":80}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"c762d2548c1746c786be882464fd5a00",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"23114f8bdcf241c688f3039672270031",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":80}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/订单详情页面/u24.png"}},
{
                  "id":"e3d2edd29195419fb2399c421db15b62",
                  "label":"",
                  "parentDynamicPanel":"23114f8bdcf241c688f3039672270031",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"ece189b5e4c840b7964ec42b234c7711",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"23114f8bdcf241c688f3039672270031",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/订单详情页面/u26.png"}},
{
                  "id":"3723cbae674e4483931bcf20ce2dfcf5",
                  "label":"",
                  "parentDynamicPanel":"23114f8bdcf241c688f3039672270031",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":10},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"ed6ee79f12d24c018a5f2e1b62a0a8cd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"23114f8bdcf241c688f3039672270031",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":80,
                          "y":10},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"1fc5e1dc62454c6488e84ba0c24303b0",
                  "label":"",
                  "parentDynamicPanel":"23114f8bdcf241c688f3039672270031",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":32},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"354048c2425648c38bc88216ae192d84",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"23114f8bdcf241c688f3039672270031",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":80,
                          "y":32},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"3601d8b194354081a10a0612f9c73e42",
                  "label":"",
                  "parentDynamicPanel":"23114f8bdcf241c688f3039672270031",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":54},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"042cc55386c04104a0bff3c53519f5b9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"23114f8bdcf241c688f3039672270031",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":80,
                          "y":54},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"8660e408ddf344549a76a10068850f0f",
                  "label":"",
                  "parentDynamicPanel":"23114f8bdcf241c688f3039672270031",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":230,
                      "y":24},
                    "size":{
                      "width":70,
                      "height":32}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 项目流程",
                              "target":{
                                "targetType":"page",
                                "url":"项目流程.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}]},
{
          "id":"9e4d06cae6c24e9eb156f730557d526e",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":270},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"8592929d17854486a5a9785f2ed14acb",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7194b46bd17b4b3e94cbafd852117fc6",
                  "label":"",
                  "parentDynamicPanel":"9e4d06cae6c24e9eb156f730557d526e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":80}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"e179183b057c48679b3997f7cbac9502",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9e4d06cae6c24e9eb156f730557d526e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":80}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/订单详情页面/u24.png"}},
{
                  "id":"bf82f7c0c05a4a909ca89cd04c2cf1d9",
                  "label":"",
                  "parentDynamicPanel":"9e4d06cae6c24e9eb156f730557d526e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"b07b47a879114f12a6fb9907361bfe89",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9e4d06cae6c24e9eb156f730557d526e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/订单详情页面/u26.png"}},
{
                  "id":"963bd9f53745438cb43e19c0e25f59a4",
                  "label":"",
                  "parentDynamicPanel":"9e4d06cae6c24e9eb156f730557d526e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":10},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"3a2f6d9038ae4237b45785a873582060",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9e4d06cae6c24e9eb156f730557d526e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":80,
                          "y":10},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"1aa13eadeea5454596f3b1ef152caf73",
                  "label":"",
                  "parentDynamicPanel":"9e4d06cae6c24e9eb156f730557d526e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":32},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"62c20dc7dc6647a7954957ee031939f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9e4d06cae6c24e9eb156f730557d526e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":80,
                          "y":32},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"b143feea9b504346bf595cbd1c35949c",
                  "label":"",
                  "parentDynamicPanel":"9e4d06cae6c24e9eb156f730557d526e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":54},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"f38265e74fc04b7096f78b384cbb6cf4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9e4d06cae6c24e9eb156f730557d526e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":80,
                          "y":54},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"5410ddd0ce81491e94ddce02c0e22400",
                  "label":"",
                  "parentDynamicPanel":"9e4d06cae6c24e9eb156f730557d526e",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":230,
                      "y":24},
                    "size":{
                      "width":70,
                      "height":32}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 项目流程",
                              "target":{
                                "targetType":"page",
                                "url":"项目流程.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}]},
{
          "id":"b110495799854594938e505e2a16823d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":267},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":196,
                "height":16}}},
          "objects":[{
              "id":"d4e10adbaf1045ed9be99e45bfe7ac97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":368,
                  "y":267},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"d829651b4cff456d81eba72e7132f69f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":350},
            "size":{
              "width":320,
              "height":200}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"1d2a54e408ed454f96e03cc8f8cc94e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":350},
                "size":{
                  "width":320,
                  "height":200}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/订单详情页面/u49.png"}},
{
          "id":"c4cfddf883ce478799d0855be6aefd7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":500},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":66,
                "height":16}}},
          "objects":[{
              "id":"83c82b4727bb4770a368185f4fc13b5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":500},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"d76aa72a56ba44eeba0849e36d8e2a99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":524},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":27,
                "height":16}}},
          "objects":[{
              "id":"c2d3229f4b69463e8bb7f715fa757ead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":524},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"8e08349770cb4785bba66f16590bebe8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":350},
            "size":{
              "width":320,
              "height":70}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"020e9ee51cf34fe4bb011e1359a22620",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":350},
                "size":{
                  "width":320,
                  "height":70}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/订单详情页面/u55.png"}},
{
          "id":"9869cda267824d6fb72be7779069bc72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":360},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":105,
                "height":16}}},
          "objects":[{
              "id":"969f87abb7514a74b8e44cd2f21e3fad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":360},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"ec6396b49981497dabc0d1718eb0b06c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":420},
            "size":{
              "width":320,
              "height":70}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"4b136ed9d98d43838994d2e06e397161",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":420},
                "size":{
                  "width":320,
                  "height":70}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/订单详情页面/u55.png"}},
{
          "id":"72604de89ef748948ffd245206aef9af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":430},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"f0559952f48c49aa8c20ae6fb2cbd213",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":430},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"b0bbf0550cbe44baa97872d422697a8a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":560},
            "size":{
              "width":320,
              "height":30}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (HTML Button),<br>隐藏 (HTML Button)",
                      "objectsToFades":[{
                          "objectPath":["b0bbf0550cbe44baa97872d422697a8a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e4abd902cbc84c7191481c76f97a5818"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"e4abd902cbc84c7191481c76f97a5818",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":560},
            "size":{
              "width":320,
              "height":30}},
          "adaptiveStyles":{
            "a":{
              "visible":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账户余额",
                      "target":{
                        "targetType":"page",
                        "url":"账户余额.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9aae05fd061a42f4b7f78f366661d0db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":567},
            "size":{
              "width":183,
              "height":32}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":183,
                "height":32}}},
          "objects":[{
              "id":"fea1c9e61ecb415194c272870212b86c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":567},
                "size":{
                  "width":183,
                  "height":32}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}}]}},
  "masters":{
    "df7296c8ffe54f5a8275e259720d080f":{
      "packageId":"df7296c8ffe54f5a8275e259720d080f",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f268a5e8567446a2b4c3752e5c4c10db",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"f35a0677b1d849668e5fc835f159ec9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/登录界面/u0.png"}},
{
            "id":"3b3ab3937fcb4fc89546814186a00148",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":50}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"91bf4e6527e543abb9382620546d5aec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":50}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"b5e2dedc704441dbbc3bd3fdb5962aa9",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12},
              "size":{
                "width":70,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}}}]}}},
  "objectPaths":{
    "20973d8365994f5ba7c5531b80fd7d71":{
      "scriptId":"u0",
      "f268a5e8567446a2b4c3752e5c4c10db":{
        "scriptId":"u1"},
      "f35a0677b1d849668e5fc835f159ec9d":{
        "scriptId":"u2"},
      "3b3ab3937fcb4fc89546814186a00148":{
        "scriptId":"u3"},
      "91bf4e6527e543abb9382620546d5aec":{
        "scriptId":"u4"},
      "b5e2dedc704441dbbc3bd3fdb5962aa9":{
        "scriptId":"u5"}},
    "b87afb901fec4bfdaca9cc5a4922f541":{
      "scriptId":"u6"},
    "9c1ff02a5a694aebae0614fe9dc08441":{
      "scriptId":"u7"},
    "a629fb25bb48430f9b9e03a6bcbb0b77":{
      "scriptId":"u8"},
    "b4c583531fb0460eaac14e492d39d7c9":{
      "scriptId":"u9"},
    "c1f54f7bc0514a088b665e3d11678ebb":{
      "scriptId":"u10"},
    "6de7e3e051934305a9a4d5f1e5f9181a":{
      "scriptId":"u11"},
    "b98fcc64610845e49c3c78a31a7f6033":{
      "scriptId":"u12"},
    "49d57e39954f475baa6f2d5094a24115":{
      "scriptId":"u13"},
    "c8324e40ea3648d79796ba60437a1a25":{
      "scriptId":"u14"},
    "f38afb9e27b2448087f9df8143157ea9":{
      "scriptId":"u15"},
    "69547f8620734a86ad870ffcc51c6bf7":{
      "scriptId":"u16"},
    "4864e65259dd4b8ba22a50fc67743efa":{
      "scriptId":"u17"},
    "0678aaace7ac4e3988ccc0275b827bb7":{
      "scriptId":"u18"},
    "709a3d66e3c74fceb849ac302497403f":{
      "scriptId":"u19"},
    "57afb92a0e4349f386ad9dece6e6725c":{
      "scriptId":"u20"},
    "3b2ccaa7ce854bbc8685b9b16b33bb4c":{
      "scriptId":"u21"},
    "4bc02d41da3040888f0dd5ededb3cd6e":{
      "scriptId":"u22"},
    "23114f8bdcf241c688f3039672270031":{
      "scriptId":"u23"},
    "c880b924fe944950b104273ee734aae9":{
      "scriptId":"u24"},
    "c762d2548c1746c786be882464fd5a00":{
      "scriptId":"u25"},
    "e3d2edd29195419fb2399c421db15b62":{
      "scriptId":"u26"},
    "ece189b5e4c840b7964ec42b234c7711":{
      "scriptId":"u27"},
    "3723cbae674e4483931bcf20ce2dfcf5":{
      "scriptId":"u28"},
    "ed6ee79f12d24c018a5f2e1b62a0a8cd":{
      "scriptId":"u29"},
    "1fc5e1dc62454c6488e84ba0c24303b0":{
      "scriptId":"u30"},
    "354048c2425648c38bc88216ae192d84":{
      "scriptId":"u31"},
    "3601d8b194354081a10a0612f9c73e42":{
      "scriptId":"u32"},
    "042cc55386c04104a0bff3c53519f5b9":{
      "scriptId":"u33"},
    "8660e408ddf344549a76a10068850f0f":{
      "scriptId":"u34"},
    "9e4d06cae6c24e9eb156f730557d526e":{
      "scriptId":"u35"},
    "7194b46bd17b4b3e94cbafd852117fc6":{
      "scriptId":"u36"},
    "e179183b057c48679b3997f7cbac9502":{
      "scriptId":"u37"},
    "bf82f7c0c05a4a909ca89cd04c2cf1d9":{
      "scriptId":"u38"},
    "b07b47a879114f12a6fb9907361bfe89":{
      "scriptId":"u39"},
    "963bd9f53745438cb43e19c0e25f59a4":{
      "scriptId":"u40"},
    "3a2f6d9038ae4237b45785a873582060":{
      "scriptId":"u41"},
    "1aa13eadeea5454596f3b1ef152caf73":{
      "scriptId":"u42"},
    "62c20dc7dc6647a7954957ee031939f6":{
      "scriptId":"u43"},
    "b143feea9b504346bf595cbd1c35949c":{
      "scriptId":"u44"},
    "f38265e74fc04b7096f78b384cbb6cf4":{
      "scriptId":"u45"},
    "5410ddd0ce81491e94ddce02c0e22400":{
      "scriptId":"u46"},
    "b110495799854594938e505e2a16823d":{
      "scriptId":"u47"},
    "d4e10adbaf1045ed9be99e45bfe7ac97":{
      "scriptId":"u48"},
    "d829651b4cff456d81eba72e7132f69f":{
      "scriptId":"u49"},
    "1d2a54e408ed454f96e03cc8f8cc94e3":{
      "scriptId":"u50"},
    "c4cfddf883ce478799d0855be6aefd7e":{
      "scriptId":"u51"},
    "83c82b4727bb4770a368185f4fc13b5a":{
      "scriptId":"u52"},
    "d76aa72a56ba44eeba0849e36d8e2a99":{
      "scriptId":"u53"},
    "c2d3229f4b69463e8bb7f715fa757ead":{
      "scriptId":"u54"},
    "8e08349770cb4785bba66f16590bebe8":{
      "scriptId":"u55"},
    "020e9ee51cf34fe4bb011e1359a22620":{
      "scriptId":"u56"},
    "9869cda267824d6fb72be7779069bc72":{
      "scriptId":"u57"},
    "969f87abb7514a74b8e44cd2f21e3fad":{
      "scriptId":"u58"},
    "ec6396b49981497dabc0d1718eb0b06c":{
      "scriptId":"u59"},
    "4b136ed9d98d43838994d2e06e397161":{
      "scriptId":"u60"},
    "72604de89ef748948ffd245206aef9af":{
      "scriptId":"u61"},
    "f0559952f48c49aa8c20ae6fb2cbd213":{
      "scriptId":"u62"},
    "b0bbf0550cbe44baa97872d422697a8a":{
      "scriptId":"u63"},
    "e4abd902cbc84c7191481c76f97a5818":{
      "scriptId":"u64"},
    "9aae05fd061a42f4b7f78f366661d0db":{
      "scriptId":"u65"},
    "fea1c9e61ecb415194c272870212b86c":{
      "scriptId":"u66"}}});