$axure.loadCurrentPage({
  "url":"单个产品介绍.html",
  "generationDate":new Date(1421557821692.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0026001ef3994beca209bbbdfb508097",
    "type":"Axure:Page",
    "name":"单个产品介绍",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ecdc2d175d3046948c83a1abc36a53d9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"df7296c8ffe54f5a8275e259720d080f"},
{
          "id":"68971bac44f64928b0f5e9c1d12ea2f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":10},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":81,
                "height":23}}},
          "objects":[{
              "id":"d70700fd3e09444e8ea515fe3c829417",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":10},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"e2c154778f3442dc8f8ee6e3270747e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":290,
              "height":210}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"74e727f0b7c84802b71da3960cb5ea61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":60},
                "size":{
                  "width":290,
                  "height":210}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/单个产品介绍/u8.png"}},
{
          "id":"0464e2a35ea045bc8cf1b66fc908b4b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":290},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"6f7e9f7a4afb47c6ab7d8938c01fe4d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":290},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bf4f60fa0b044c99395425e205dbf04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":324},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"930fe17e011d477dab7656b7103121ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":324},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ad38772054e4263a0d0668388edebe0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":356},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"8f97de51e3b846ec92f11b261ea9745b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":356},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1aab036c76a240e5801aa853878b799e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":388},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"5a6d833a2f0642ea926bed85b55e95e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":388},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc64887dbeeb4f85bed61b2a28c751a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":444},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"2c4c066604d0414d86757472a8900c14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":444},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "df7296c8ffe54f5a8275e259720d080f":{
      "packageId":"df7296c8ffe54f5a8275e259720d080f",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f268a5e8567446a2b4c3752e5c4c10db",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"f35a0677b1d849668e5fc835f159ec9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/登录界面/u0.png"}},
{
            "id":"3b3ab3937fcb4fc89546814186a00148",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":50}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"91bf4e6527e543abb9382620546d5aec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":50}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"b5e2dedc704441dbbc3bd3fdb5962aa9",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12},
              "size":{
                "width":70,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}}}]}}},
  "objectPaths":{
    "ecdc2d175d3046948c83a1abc36a53d9":{
      "scriptId":"u0",
      "f268a5e8567446a2b4c3752e5c4c10db":{
        "scriptId":"u1"},
      "f35a0677b1d849668e5fc835f159ec9d":{
        "scriptId":"u2"},
      "3b3ab3937fcb4fc89546814186a00148":{
        "scriptId":"u3"},
      "91bf4e6527e543abb9382620546d5aec":{
        "scriptId":"u4"},
      "b5e2dedc704441dbbc3bd3fdb5962aa9":{
        "scriptId":"u5"}},
    "68971bac44f64928b0f5e9c1d12ea2f1":{
      "scriptId":"u6"},
    "d70700fd3e09444e8ea515fe3c829417":{
      "scriptId":"u7"},
    "e2c154778f3442dc8f8ee6e3270747e7":{
      "scriptId":"u8"},
    "74e727f0b7c84802b71da3960cb5ea61":{
      "scriptId":"u9"},
    "0464e2a35ea045bc8cf1b66fc908b4b2":{
      "scriptId":"u10"},
    "6f7e9f7a4afb47c6ab7d8938c01fe4d8":{
      "scriptId":"u11"},
    "6bf4f60fa0b044c99395425e205dbf04":{
      "scriptId":"u12"},
    "930fe17e011d477dab7656b7103121ec":{
      "scriptId":"u13"},
    "5ad38772054e4263a0d0668388edebe0":{
      "scriptId":"u14"},
    "8f97de51e3b846ec92f11b261ea9745b":{
      "scriptId":"u15"},
    "1aab036c76a240e5801aa853878b799e":{
      "scriptId":"u16"},
    "5a6d833a2f0642ea926bed85b55e95e2":{
      "scriptId":"u17"},
    "cc64887dbeeb4f85bed61b2a28c751a8":{
      "scriptId":"u18"},
    "2c4c066604d0414d86757472a8900c14":{
      "scriptId":"u19"}}});