$axure.loadCurrentPage({
  "url":"我的排期.html",
  "generationDate":new Date(1421491591462.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fffc4250ba95435ca9892983b2684d86",
    "type":"Axure:Page",
    "name":"我的排期",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5649b10aaa0c4b75ac8149f8f2892931",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c9244275e3aa436b9ff9b6a761fafe54"},
{
          "id":"98708a62ecaf4db7a347627d4b1c6fc2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":420}},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"51712b1429cd4cfca22a4342d969f383"},
{
          "id":"2b4af23d52d5415480c3fa21779ff6a1",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"84bb8662c3ba418587075fd1026952e7",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"af0d94356ee0427989d76ccf4fada94d",
                  "label":"",
                  "parentDynamicPanel":"2b4af23d52d5415480c3fa21779ff6a1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":70,
                      "height":370}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"3ded70dd6c4a4efe97be434f2d3851d2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b4af23d52d5415480c3fa21779ff6a1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":70,
                          "height":370}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的排期/u14.png"}},
{
                  "id":"a7c5ae3fa9e34a9ea954ff8820dfb355",
                  "label":"",
                  "parentDynamicPanel":"2b4af23d52d5415480c3fa21779ff6a1",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}}},
{
                  "id":"0a13eb93361846b0bd4919c2389db1b8",
                  "label":"",
                  "parentDynamicPanel":"2b4af23d52d5415480c3fa21779ff6a1",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}}},
{
                  "id":"b268893bd6754a48b5a58c852d053e7b",
                  "label":"",
                  "parentDynamicPanel":"2b4af23d52d5415480c3fa21779ff6a1",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}}},
{
                  "id":"a87ede8c098b4326be98215851203406",
                  "label":"",
                  "parentDynamicPanel":"2b4af23d52d5415480c3fa21779ff6a1",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}}},
{
                  "id":"d5ffb3834950432281681da193a01e01",
                  "label":"",
                  "parentDynamicPanel":"2b4af23d52d5415480c3fa21779ff6a1",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":160},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}}},
{
                  "id":"e49e8044a7444814bbc0e8fe3fbc5fc3",
                  "label":"",
                  "parentDynamicPanel":"2b4af23d52d5415480c3fa21779ff6a1",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":200},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}}},
{
                  "id":"f070f941833447d9a84105648b49af6d",
                  "label":"",
                  "parentDynamicPanel":"2b4af23d52d5415480c3fa21779ff6a1",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":70,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}}}]}]},
{
          "id":"695ad69f59cd4b1eb727fa7951b31478",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":50},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"9c583efc7aec4bbb88f907966938cfa5",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3e70c45903e141b592199dd3c232c9e0",
                  "label":"",
                  "parentDynamicPanel":"695ad69f59cd4b1eb727fa7951b31478",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":70}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"7a94b83a5230402393df5e08dcd602b4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"695ad69f59cd4b1eb727fa7951b31478",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":70}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的排期/u24.png"}},
{
                  "id":"710a7516a264464a821dadbde61158c5",
                  "label":"",
                  "parentDynamicPanel":"695ad69f59cd4b1eb727fa7951b31478",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":102,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":102,
                        "height":16}}},
                  "objects":[{
                      "id":"eb95bdcb626c4e61ae2b77fbcfac47a3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"695ad69f59cd4b1eb727fa7951b31478",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":102,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"1fb46a0243224e32b9d3e38f8bd76e6d",
                  "label":"",
                  "parentDynamicPanel":"695ad69f59cd4b1eb727fa7951b31478",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":36},
                    "size":{
                      "width":104,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":104,
                        "height":16}}},
                  "objects":[{
                      "id":"d8ec0d49131c4a9c94243454678379c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"695ad69f59cd4b1eb727fa7951b31478",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":36},
                        "size":{
                          "width":104,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"acd3b41ef46a4acd8a5ef77091a37ffb",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":120},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"652c89b9336d494a917e7dfe7b0c6c97",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7d81aa80b9734823b94ab3b0920f36ef",
                  "label":"",
                  "parentDynamicPanel":"acd3b41ef46a4acd8a5ef77091a37ffb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":70}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"f0c443bf63474218b6727cbb3c195e95",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"acd3b41ef46a4acd8a5ef77091a37ffb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":70}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的排期/u24.png"}},
{
                  "id":"1ac8d5204c1f46e8b09a0fa299e14fd5",
                  "label":"",
                  "parentDynamicPanel":"acd3b41ef46a4acd8a5ef77091a37ffb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":102,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":102,
                        "height":16}}},
                  "objects":[{
                      "id":"4fcbf7cfbd7348cfbe567d6ca7ff39df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"acd3b41ef46a4acd8a5ef77091a37ffb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":102,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"c7e3ece74b7242e5808f1be9083512d9",
                  "label":"",
                  "parentDynamicPanel":"acd3b41ef46a4acd8a5ef77091a37ffb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":36},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":78,
                        "height":16}}},
                  "objects":[{
                      "id":"d1752dbe26a7415bbc6676046bb9ad4b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"acd3b41ef46a4acd8a5ef77091a37ffb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":36},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"4cbc706f74944a8ba9f443893419760b",
                  "label":"",
                  "parentDynamicPanel":"acd3b41ef46a4acd8a5ef77091a37ffb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":36},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":78,
                        "height":16},
                      "visible":false}},
                  "objects":[{
                      "id":"03767eed4d8744479927016e9ac1ad79",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"acd3b41ef46a4acd8a5ef77091a37ffb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":36},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"a85d71f9fcb84897b69b95a3a1c68876",
                  "label":"",
                  "parentDynamicPanel":"acd3b41ef46a4acd8a5ef77091a37ffb",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":22},
                    "size":{
                      "width":80,
                      "height":30}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 (HTML Button)",
                              "objectsToFades":[{
                                  "objectPath":["a85d71f9fcb84897b69b95a3a1c68876"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 (形状),<br>隐藏 (形状)",
                              "objectsToFades":[{
                                  "objectPath":["c7e3ece74b7242e5808f1be9083512d9"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["4cbc706f74944a8ba9f443893419760b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"ce504262ce034d7ea47509592a7de74c",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":190},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"8e139fcdb30643ed8a06ea4ce68a6f76",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f780cc6331f54617a0ead594654b406e",
                  "label":"",
                  "parentDynamicPanel":"ce504262ce034d7ea47509592a7de74c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":70}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"dbd646fa13a549dabdbbf22df158143f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ce504262ce034d7ea47509592a7de74c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":70}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的排期/u24.png"}},
{
                  "id":"ff9be00f14c3436eb5875f28075fbaf6",
                  "label":"",
                  "parentDynamicPanel":"ce504262ce034d7ea47509592a7de74c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":102,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":102,
                        "height":16}}},
                  "objects":[{
                      "id":"5f2e30265b4f43f4b584ebcad2807ef5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ce504262ce034d7ea47509592a7de74c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":102,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"81841926f541473d8cb13534fd34f4af",
                  "label":"",
                  "parentDynamicPanel":"ce504262ce034d7ea47509592a7de74c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":36},
                    "size":{
                      "width":104,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":104,
                        "height":16}}},
                  "objects":[{
                      "id":"bbe10c882c4f499982b03f1b49fb32f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ce504262ce034d7ea47509592a7de74c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":36},
                        "size":{
                          "width":104,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"cb107349fa0445199ca68930a6123457",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":260},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"4d673545aeeb4f87b154fb2571b85f22",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fdc97aa0a70d4e1ca63d40d6f34b1372",
                  "label":"",
                  "parentDynamicPanel":"cb107349fa0445199ca68930a6123457",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":70}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"6094dffa2a554f17b4bb142639e55892",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cb107349fa0445199ca68930a6123457",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":70}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的排期/u24.png"}},
{
                  "id":"421e2455a2004466b3e2e44044ea44bc",
                  "label":"",
                  "parentDynamicPanel":"cb107349fa0445199ca68930a6123457",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":102,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":102,
                        "height":16}}},
                  "objects":[{
                      "id":"0f4c194573aa4c05aba46968aef484ff",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cb107349fa0445199ca68930a6123457",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":102,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"3314de668bb047e18d120447d488ae99",
                  "label":"",
                  "parentDynamicPanel":"cb107349fa0445199ca68930a6123457",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":36},
                    "size":{
                      "width":104,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":104,
                        "height":16}}},
                  "objects":[{
                      "id":"fdb822fe863340e9946ad8ca9577ccb9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cb107349fa0445199ca68930a6123457",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":36},
                        "size":{
                          "width":104,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"b7e803b91d5046b293605d025b9e4d48",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":330},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ed0342680ea4453a8e7f9e4d6646b83e",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8bb1b01ddb954d7d85273f4b65f34603",
                  "label":"",
                  "parentDynamicPanel":"b7e803b91d5046b293605d025b9e4d48",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":70}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"1a9bb6d6c1794e93952aec6af0c1b698",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b7e803b91d5046b293605d025b9e4d48",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":70}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的排期/u24.png"}},
{
                  "id":"42aafd5da5c44079b4f3edec66b5d110",
                  "label":"",
                  "parentDynamicPanel":"b7e803b91d5046b293605d025b9e4d48",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":102,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":102,
                        "height":16}}},
                  "objects":[{
                      "id":"df01f19dce52406aa03dbc604b65cb8e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b7e803b91d5046b293605d025b9e4d48",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":102,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"67494d6fd8bf4f7dba6e0a039e9af894",
                  "label":"",
                  "parentDynamicPanel":"b7e803b91d5046b293605d025b9e4d48",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":36},
                    "size":{
                      "width":104,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":104,
                        "height":16}}},
                  "objects":[{
                      "id":"a2c64fc18b594b4ab5649b498df961e8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b7e803b91d5046b293605d025b9e4d48",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":36},
                        "size":{
                          "width":104,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"3ab65fce72f441b6a06870b73a6fd789",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":7},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":81,
                "height":23}}},
          "objects":[{
              "id":"3913227ff75c41cc80477255467cb5e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":7},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c9244275e3aa436b9ff9b6a761fafe54":{
      "packageId":"c9244275e3aa436b9ff9b6a761fafe54",
      "type":"Axure:Master",
      "name":"上导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"362ac4472cf34d7cbe59b95da5fd92f9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"7d5983b6bab84de483fd1fed0e7ba98f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/登录界面/u0.png"}},
{
            "id":"05b4fb99562b4ceea301650e882e7eb8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":50}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"9476162c387f47359880aa58e3bdf455",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":50}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"5a3fd74cc3984739a980ea09882e94f1",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12},
              "size":{
                "width":60,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}}},
{
            "id":"2e6ef4a2c9554d5b9f1cec0e24e06e53",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":249,
                "y":12},
              "size":{
                "width":60,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}}}]}},
    "51712b1429cd4cfca22a4342d969f383":{
      "packageId":"51712b1429cd4cfca22a4342d969f383",
      "type":"Axure:Master",
      "name":"底部导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"dbf88162755142e08204fcfe620f9439",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":455},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":0,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"a94363e385794ed6950cbb4c15dd73a4",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":430},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":64,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的排期",
                        "target":{
                          "targetType":"page",
                          "url":"我的排期.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"94fc8cf3d1d34f9f9eb5d0d8a2249caa",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":440},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":128,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的信息",
                        "target":{
                          "targetType":"page",
                          "url":"我的信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"ab56bfc79a1247568a0df315cb300dc8",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":450},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":192,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 平台咨询",
                        "target":{
                          "targetType":"page",
                          "url":"平台咨询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"ef2472d415f44a439e9ffc61b0368de5",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":460},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":256,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 账户余额",
                        "target":{
                          "targetType":"page",
                          "url":"账户余额.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "5649b10aaa0c4b75ac8149f8f2892931":{
      "scriptId":"u0",
      "362ac4472cf34d7cbe59b95da5fd92f9":{
        "scriptId":"u1"},
      "7d5983b6bab84de483fd1fed0e7ba98f":{
        "scriptId":"u2"},
      "05b4fb99562b4ceea301650e882e7eb8":{
        "scriptId":"u3"},
      "9476162c387f47359880aa58e3bdf455":{
        "scriptId":"u4"},
      "5a3fd74cc3984739a980ea09882e94f1":{
        "scriptId":"u5"},
      "2e6ef4a2c9554d5b9f1cec0e24e06e53":{
        "scriptId":"u6"}},
    "98708a62ecaf4db7a347627d4b1c6fc2":{
      "scriptId":"u7",
      "dbf88162755142e08204fcfe620f9439":{
        "scriptId":"u8"},
      "a94363e385794ed6950cbb4c15dd73a4":{
        "scriptId":"u9"},
      "94fc8cf3d1d34f9f9eb5d0d8a2249caa":{
        "scriptId":"u10"},
      "ab56bfc79a1247568a0df315cb300dc8":{
        "scriptId":"u11"},
      "ef2472d415f44a439e9ffc61b0368de5":{
        "scriptId":"u12"}},
    "2b4af23d52d5415480c3fa21779ff6a1":{
      "scriptId":"u13"},
    "af0d94356ee0427989d76ccf4fada94d":{
      "scriptId":"u14"},
    "3ded70dd6c4a4efe97be434f2d3851d2":{
      "scriptId":"u15"},
    "a7c5ae3fa9e34a9ea954ff8820dfb355":{
      "scriptId":"u16"},
    "0a13eb93361846b0bd4919c2389db1b8":{
      "scriptId":"u17"},
    "b268893bd6754a48b5a58c852d053e7b":{
      "scriptId":"u18"},
    "a87ede8c098b4326be98215851203406":{
      "scriptId":"u19"},
    "d5ffb3834950432281681da193a01e01":{
      "scriptId":"u20"},
    "e49e8044a7444814bbc0e8fe3fbc5fc3":{
      "scriptId":"u21"},
    "f070f941833447d9a84105648b49af6d":{
      "scriptId":"u22"},
    "695ad69f59cd4b1eb727fa7951b31478":{
      "scriptId":"u23"},
    "3e70c45903e141b592199dd3c232c9e0":{
      "scriptId":"u24"},
    "7a94b83a5230402393df5e08dcd602b4":{
      "scriptId":"u25"},
    "710a7516a264464a821dadbde61158c5":{
      "scriptId":"u26"},
    "eb95bdcb626c4e61ae2b77fbcfac47a3":{
      "scriptId":"u27"},
    "1fb46a0243224e32b9d3e38f8bd76e6d":{
      "scriptId":"u28"},
    "d8ec0d49131c4a9c94243454678379c7":{
      "scriptId":"u29"},
    "acd3b41ef46a4acd8a5ef77091a37ffb":{
      "scriptId":"u30"},
    "7d81aa80b9734823b94ab3b0920f36ef":{
      "scriptId":"u31"},
    "f0c443bf63474218b6727cbb3c195e95":{
      "scriptId":"u32"},
    "1ac8d5204c1f46e8b09a0fa299e14fd5":{
      "scriptId":"u33"},
    "4fcbf7cfbd7348cfbe567d6ca7ff39df":{
      "scriptId":"u34"},
    "c7e3ece74b7242e5808f1be9083512d9":{
      "scriptId":"u35"},
    "d1752dbe26a7415bbc6676046bb9ad4b":{
      "scriptId":"u36"},
    "4cbc706f74944a8ba9f443893419760b":{
      "scriptId":"u37"},
    "03767eed4d8744479927016e9ac1ad79":{
      "scriptId":"u38"},
    "a85d71f9fcb84897b69b95a3a1c68876":{
      "scriptId":"u39"},
    "ce504262ce034d7ea47509592a7de74c":{
      "scriptId":"u40"},
    "f780cc6331f54617a0ead594654b406e":{
      "scriptId":"u41"},
    "dbd646fa13a549dabdbbf22df158143f":{
      "scriptId":"u42"},
    "ff9be00f14c3436eb5875f28075fbaf6":{
      "scriptId":"u43"},
    "5f2e30265b4f43f4b584ebcad2807ef5":{
      "scriptId":"u44"},
    "81841926f541473d8cb13534fd34f4af":{
      "scriptId":"u45"},
    "bbe10c882c4f499982b03f1b49fb32f3":{
      "scriptId":"u46"},
    "cb107349fa0445199ca68930a6123457":{
      "scriptId":"u47"},
    "fdc97aa0a70d4e1ca63d40d6f34b1372":{
      "scriptId":"u48"},
    "6094dffa2a554f17b4bb142639e55892":{
      "scriptId":"u49"},
    "421e2455a2004466b3e2e44044ea44bc":{
      "scriptId":"u50"},
    "0f4c194573aa4c05aba46968aef484ff":{
      "scriptId":"u51"},
    "3314de668bb047e18d120447d488ae99":{
      "scriptId":"u52"},
    "fdb822fe863340e9946ad8ca9577ccb9":{
      "scriptId":"u53"},
    "b7e803b91d5046b293605d025b9e4d48":{
      "scriptId":"u54"},
    "8bb1b01ddb954d7d85273f4b65f34603":{
      "scriptId":"u55"},
    "1a9bb6d6c1794e93952aec6af0c1b698":{
      "scriptId":"u56"},
    "42aafd5da5c44079b4f3edec66b5d110":{
      "scriptId":"u57"},
    "df01f19dce52406aa03dbc604b65cb8e":{
      "scriptId":"u58"},
    "67494d6fd8bf4f7dba6e0a039e9af894":{
      "scriptId":"u59"},
    "a2c64fc18b594b4ab5649b498df961e8":{
      "scriptId":"u60"},
    "3ab65fce72f441b6a06870b73a6fd789":{
      "scriptId":"u61"},
    "3913227ff75c41cc80477255467cb5e8":{
      "scriptId":"u62"}}});