$axure.loadCurrentPage({
  "url":"单个流程介绍.html",
  "generationDate":new Date(1421557821432.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f2d0375138454af28e41e1d427869a0e",
    "type":"Axure:Page",
    "name":"单个流程介绍",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5571d5ecae054894a3babf866fcfff43",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"df7296c8ffe54f5a8275e259720d080f"},
{
          "id":"46fe18b4b9cd4b85ae1915462254bcf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":100,
              "y":13},
            "size":{
              "width":121,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":121,
                "height":23}}},
          "objects":[{
              "id":"a2651cb952dc4f22917454976f286f04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":100,
                  "y":13},
                "size":{
                  "width":121,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"8d66c2ca95ce4b76beeb750e428673d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":70},
            "size":{
              "width":260,
              "height":200}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"0db8b519689f4152a62fbc6f9e1db534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":70},
                "size":{
                  "width":260,
                  "height":200}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/单个流程介绍/u8.png"}},
{
          "id":"8250251feffc4b799c037f26397a724e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":294},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"344ed76831fa42cf86f193d505a053fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":294},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"562c6464bd7041729f4f6a93fe9406fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":350},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"ed7f306e99b34b8da108d19514f5a3ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":350},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"548fe22b1067423b85a8d55a390dcaa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":400},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"8762b8f320474a5d8654a8c9bbfcf0d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":400},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "df7296c8ffe54f5a8275e259720d080f":{
      "packageId":"df7296c8ffe54f5a8275e259720d080f",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f268a5e8567446a2b4c3752e5c4c10db",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"f35a0677b1d849668e5fc835f159ec9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/登录界面/u0.png"}},
{
            "id":"3b3ab3937fcb4fc89546814186a00148",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":50}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"91bf4e6527e543abb9382620546d5aec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":50}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"b5e2dedc704441dbbc3bd3fdb5962aa9",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12},
              "size":{
                "width":70,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}}}]}}},
  "objectPaths":{
    "5571d5ecae054894a3babf866fcfff43":{
      "scriptId":"u0",
      "f268a5e8567446a2b4c3752e5c4c10db":{
        "scriptId":"u1"},
      "f35a0677b1d849668e5fc835f159ec9d":{
        "scriptId":"u2"},
      "3b3ab3937fcb4fc89546814186a00148":{
        "scriptId":"u3"},
      "91bf4e6527e543abb9382620546d5aec":{
        "scriptId":"u4"},
      "b5e2dedc704441dbbc3bd3fdb5962aa9":{
        "scriptId":"u5"}},
    "46fe18b4b9cd4b85ae1915462254bcf8":{
      "scriptId":"u6"},
    "a2651cb952dc4f22917454976f286f04":{
      "scriptId":"u7"},
    "8d66c2ca95ce4b76beeb750e428673d7":{
      "scriptId":"u8"},
    "0db8b519689f4152a62fbc6f9e1db534":{
      "scriptId":"u9"},
    "8250251feffc4b799c037f26397a724e":{
      "scriptId":"u10"},
    "344ed76831fa42cf86f193d505a053fe":{
      "scriptId":"u11"},
    "562c6464bd7041729f4f6a93fe9406fd":{
      "scriptId":"u12"},
    "ed7f306e99b34b8da108d19514f5a3ac":{
      "scriptId":"u13"},
    "548fe22b1067423b85a8d55a390dcaa1":{
      "scriptId":"u14"},
    "8762b8f320474a5d8654a8c9bbfcf0d9":{
      "scriptId":"u15"}}});