$axure.loadCurrentPage({
  "url":"项目流程.html",
  "generationDate":new Date(1421491595192.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2569fea40a0047e8b681057c475bc8e8",
    "type":"Axure:Page",
    "name":"项目流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6f92cf8e8c46415daa6284f34968f163",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"df7296c8ffe54f5a8275e259720d080f"},
{
          "id":"496f61e079724370a03b8593f05f7df5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":10},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":10},
              "size":{
                "width":81,
                "height":23}}},
          "objects":[{
              "id":"7eba92997b304cb7805f6dda27cbde4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":10},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"cf45ef9f109c4ff4a31811c398470394",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":320,
              "height":90}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"4f373ae5a3394c7999fcf82768ecf071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":320,
                  "height":90}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/项目流程/u8.png"}},
{
          "id":"ef1e55a233e842fcb8cc05049eb4f18f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":150},
            "size":{
              "width":320,
              "height":140}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"3eb32527134943b1aa47f3be77f503c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":320,
                  "height":140}},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 单个流程介绍",
                      "target":{
                        "targetType":"page",
                        "url":"单个流程介绍.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/项目流程/u10.png"}},
{
          "id":"619d98f93f284cd3964e8da81d200b2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":300},
            "size":{
              "width":320,
              "height":100}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"a17f709cb9d84768afb82b135f282c58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":300},
                "size":{
                  "width":320,
                  "height":100}},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 单个产品介绍",
                      "target":{
                        "targetType":"page",
                        "url":"单个产品介绍.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/平台咨询/u16.png"}},
{
          "id":"12d716c77408437f8fdbee7e18148d8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":410},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"d38788aadde5457aac701709e2df72e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":410},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"899b0d4f7c50453eab854067cc6766d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":436},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":27,
                "height":16}}},
          "objects":[{
              "id":"73277cde9f66419f8239ecfab623e04e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":436},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}}]}},
  "masters":{
    "df7296c8ffe54f5a8275e259720d080f":{
      "packageId":"df7296c8ffe54f5a8275e259720d080f",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f268a5e8567446a2b4c3752e5c4c10db",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"f35a0677b1d849668e5fc835f159ec9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/登录界面/u0.png"}},
{
            "id":"3b3ab3937fcb4fc89546814186a00148",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":50}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"91bf4e6527e543abb9382620546d5aec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":50}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"b5e2dedc704441dbbc3bd3fdb5962aa9",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12},
              "size":{
                "width":70,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}}}]}}},
  "objectPaths":{
    "6f92cf8e8c46415daa6284f34968f163":{
      "scriptId":"u0",
      "f268a5e8567446a2b4c3752e5c4c10db":{
        "scriptId":"u1"},
      "f35a0677b1d849668e5fc835f159ec9d":{
        "scriptId":"u2"},
      "3b3ab3937fcb4fc89546814186a00148":{
        "scriptId":"u3"},
      "91bf4e6527e543abb9382620546d5aec":{
        "scriptId":"u4"},
      "b5e2dedc704441dbbc3bd3fdb5962aa9":{
        "scriptId":"u5"}},
    "496f61e079724370a03b8593f05f7df5":{
      "scriptId":"u6"},
    "7eba92997b304cb7805f6dda27cbde4d":{
      "scriptId":"u7"},
    "cf45ef9f109c4ff4a31811c398470394":{
      "scriptId":"u8"},
    "4f373ae5a3394c7999fcf82768ecf071":{
      "scriptId":"u9"},
    "ef1e55a233e842fcb8cc05049eb4f18f":{
      "scriptId":"u10"},
    "3eb32527134943b1aa47f3be77f503c1":{
      "scriptId":"u11"},
    "619d98f93f284cd3964e8da81d200b2e":{
      "scriptId":"u12"},
    "a17f709cb9d84768afb82b135f282c58":{
      "scriptId":"u13"},
    "12d716c77408437f8fdbee7e18148d8c":{
      "scriptId":"u14"},
    "d38788aadde5457aac701709e2df72e3":{
      "scriptId":"u15"},
    "899b0d4f7c50453eab854067cc6766d1":{
      "scriptId":"u16"},
    "73277cde9f66419f8239ecfab623e04e":{
      "scriptId":"u17"}}});